id: I28733C25
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:09:45+00:00'
last_modified: '2022-06-08T14:21:49.279980+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27939
  title: མ་ཎི་བཀའ་འབུམ་ལས་སྨད་ཀྱི་ཆ་ཞལ་གདམས་ཀྱི་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F23E:
      image_group_id: I4532
      title: ''
      total_pages: 664
      order: 1
      base_file: F23E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
