id: P010541
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27939
  title: མ་ཎི་བཀའ་འབུམ་ལས་སྨད་ཀྱི་ཆ་ཞལ་གདམས་ཀྱི་སྐོར
  author: ''
  volumes:
    1ca2c357a6aa444bb7579e024e6b7f20:
      image_group_id: I4532
      title: ''
      volume_number: 1
      total_pages: 664
      base_file: v001.txt
